{{
    config(
        materialized='table'
    )
}}

SELECT * 
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.QUERY_HISTORY(
    RESULT_LIMIT => 10000
))
WHERE QUERY_TYPE = 'ALTER'
ORDER BY START_TIME DESC
LIMIT 5000